package:
  name: conjure
  version: "{{ PACKAGE_VERSION }}"

source:
  - path: ../

requirements:
  # See here: https://conda.io/docs/spec.html?highlight=version#package-match-specifications
  build:
    - python {{python}}
    - setuptools
    - enum34 # [py<34]
    - requests
    - typing

  run:
    - enum34 # [py<34]
    - requests
    - typing

build:
  noarch_python: True

test:
  imports:
    - conjure
    - httpremoting

about:
  home: https://github.com/palantir/conjure-python-client
